name: crypto-watcher
version: 0.1.0
summary: A Flutter app for monitoring cryptocurrency prices
description: Crypto Watcher is a Flutter app that allows you to monitor cryptocurrency prices and receive notifications when prices reach certain thresholds.

confinement: strict
base: core18
grade: stable

slots: 
  dbus-crypto-watcher: 
    interface: dbus
    bus: session
    name: com.kranthi.crypto-watcher

apps: 
  crypto-watcher: 
    command: crypto_watcher 
    extensions: [flutter-master]
    plugs: 
      - network
    slots: 
      - dbus-crypto-watcher
    environment:
      DBUS_SESSION_BUS_ADDRESS: $DBUS_SESSION_BUS_ADDRESS

parts: 
  crypto-watcher: 
    source: . 
    plugin: flutter 
    flutter-target: lib/main.dart
